In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from dateutil.parser import parse

In [85]:
FILEPATH_2020 = "with_closed_ations_as________select_app_2020_X5_STORES.csv"
FILEPATH_2019 = "with_closed_ations_as________select_app_2019_X5_STORES.csv"
FILEPATH_2018 = "with_closed_ations_as________select_app_2018_X5_STORES.csv"
df = pd.read_csv(FILEPATH_2019)

/home/lev/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [86]:
df = df[df['position_name'] == 'Продавец-кассир']
df = df[df['is_active_action'] == True]
df = df.drop('is_active_action', axis=1)
df['action_date'] = df['action_date'].str[:19]
df['action_date'] = pd.to_datetime(df['action_date'], format="%Y-%m-%d %H:%M:%S")

In [29]:
df

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
3245,4774172,3835783,-1,31992,2020-03-18 07:09:13.105863+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
214958,4774172,3835783,26666690,31992,2020-03-26 14:48:20.719833+00,Оформление,Узнать результаты приема,Принят,Продавец-кассир,True,False
214959,4774172,3835783,26666679,31992,2020-03-26 14:48:05.111505+00,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем,Продавец-кассир,True,False
214960,4774172,3835783,26649216,31992,2020-03-26 10:03:58.809604+00,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,True,False

In [7]:
df[df['is_active_action'] == False]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
341,4808717,3819705,-1,11867,2020-03-25 16:30:40.955961+00,Создание кандидата,NaN,NaN,Администратор,False,False
877,4810706,3854736,-1,6325,2020-03-26 10:11:16.009413+00,Создание кандидата,NaN,NaN,Продавец-кассир,False,False
1015,4814888,2488253,-1,11037,2020-03-27 09:13:33.870314+00,Создание кандидата,NaN,NaN,Продавец-кассир,False,False
1096,4814717,3856712,-1,32815,2020-03-27 08:31:09.608313+00,Создание кандидата,NaN,NaN,Продавец-кассир,False,False
1414,4801029,3849575,-1,11134,2020-03-24 14:08:35.741229+00,Создание кандидата,NaN,NaN,Старший Продавец-кассир,False,False
...,...,...,...,...,...,...,...,...,...,...,...
739486,4729069,2317788,-1,30844,2020-04-23 16:26:11.80918+00,Обработка,Провести первичную обработку,NaN,Администратор,False,True
739534,4790647,3582921,-1,31034,2020-04-23 16:26:11.80918+00,Обработка,Проверка формы обращения,NaN,Продавец-кассир,False,True
739541,4669579,2471869,-1,31087,2020-04-23 16:26:11.80918+00,СБ,Подготовить анкету кандидата,NaN,Продавец-кассир,False,True
739545,4606237,3093534,-1,31150,2020-04-23 16:26:11.80918+00,Обработка,Провести первичную обработку,NaN,Продавец-кассир,False,True
739663,4820831,3470886,-1,31990,2020-04-23 16:26:11.80918+00,Обработка,Провести первичную обработку,NaN,Пекарь,False,True

In [ ]:
df[df['is_active_action'] == False]

In [19]:
df['stage_name'].unique()

array(['Создание кандидата', 'Интервью с руководителем', 'Обработка',
       'Оформление', 'Смена вакансии', 'СБ', 'Не прошел СБ',
       'Мы отказали', 'Выход на работу', 'Отказался', 'Резерв',
       'Черный список'], dtype=object)

In [163]:
# df[df['stage_name'] == 'Выход на работу']

In [8]:
# df[df['stage_name'] == 'Оформление']

In [25]:
df['activity_name'].unique()

array([nan, 'Узнать результаты интервью с руководителем',
       'Назначить интервью с руководителем', 'Проверка формы обращения',
       'Провести первичную обработку',
       'Предоставить обратную связь по кандидату',
       'Назначить время на оформление', 'Узнать результаты СБ',
       'Подготовить анкету кандидата', 'Узнать результаты приема',
       'Вывести из черного списка'], dtype=object)

In [57]:
df['result_name'].unique()

array([nan, 'Отказ кандидата', 'Не резерв', 'Подходит', 'Не подходит',
       'ОС не предоставлена руководителем', 'Отказ руководителя',
       'Недозвон', 'Перенос звонка', 'Встреча назначена', 'Подготовлена',
       'Резерв', 'Принят', 'ОС предоставлена руководителем',
       'Время назначено', 'Нет обратной связи от руководителя',
       'В белый список', 'Перенос кандидата', 'Нет обратной связи',
       'Не принят', 'Черный список', 'Перенос руководителя',
       'Уточнение данных'], dtype=object)

In [18]:
df[df['id_applicant'] == 4798973]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
7099,4798973,1387757,-1,35388,2020-03-24 10:39:37,Создание кандидата,NaN,NaN,Продавец-кассир,False
314224,4798973,1387757,26577377,35388,2020-03-24 10:39:49,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
314225,4798973,1387757,26577381,35388,2020-03-24 10:39:50,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
314226,4798973,1387757,26577405,35388,2020-03-24 10:40:07,Интервью с руководителем,Назначить интервью с руководителем,Перенос звонка,Продавец-кассир,False
314227,4798973,1387757,26676916,35388,2020-03-26 19:08:40,Смена вакансии,NaN,NaN,Продавец-кассир,False

In [74]:
df_new = df[['id_applicant','stage_name','activity_name','result_name']]
df_new = df_new.sort_values('id_applicant')
df_new = df_new[df_new['stage_name'] != 'Создание кандидата']

In [75]:
df_new.to_csv('unique2.csv')

In [73]:
df_new = df[['stage_name','activity_name','result_name']]
df_new = df_new.drop_duplicates().sort_values('stage_name')

In [18]:
df_new.to_csv('unique.csv')

In [21]:
df.groupby('id_applicant').count().sort_values('action_date')

,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
id_applicant,,,,,,,,,
4461761,1,1,1,1,1,0,0,1,1
4687013,1,1,1,1,1,0,0,1,1
4687007,1,1,1,1,1,0,0,1,1
4687006,1,1,1,1,1,0,0,1,1
4687003,1,1,1,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...
4811435,29,29,29,29,29,28,28,29,29
4814936,30,30,30,30,30,29,28,30,30
4700471,31,31,31,31,31,29,29,31,31
4788781,31,31,31,31,31,28,29,31,31
4784167,34,34,34,34,34,31,32,34,34

In [4]:
df[df['id_applicant'] == 4784167].drop(['id_log', 'is_open_action', 'position_name'], axis=1).sort_values('action_date')

,id_applicant,id_partner,department_id,action_date,stage_name,activity_name,result_name
182109,4784167,3339623,49607,2020-03-19 16:25:55,Создание кандидата,NaN,NaN
625663,4784167,3339623,49607,2020-03-19 16:26:12,Обработка,Провести первичную обработку,Подходит
625664,4784167,3339623,49607,2020-03-19 16:26:13,Обработка,Проверка формы обращения,Не резерв
625665,4784167,3339623,49607,2020-03-19 16:26:44,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
625666,4784167,3339623,49607,2020-03-20 15:44:50,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
625667,4784167,3339623,49607,2020-03-20 15:44:51,СБ,Подготовить анкету кандидата,Подготовлена
625668,4784167,3339623,49607,2020-03-20 17:27:26,СБ,Узнать результаты СБ,Подходит
625669,4784167,3339623,49607,2020-03-20 17:27:27,СБ,Проверка формы обращения,Не резерв
625670,4784167,3339623,49607,2020-03-21 17:49:34,Оформление,Назначить время на оформление,Время назначено
625680,4784167,3339623,49607,2020-03-24 11:16:57,Оформление,Узнать результаты приема,Перенос звонка
625671,4784167,3339623,49607,2020-03-25 16:23:06,Оформление,Узнать результаты приема,Недозвон
625672,4784167,3339623,49607,2020-03-26 17:24:45,Оформление,Узнать результаты приема,Недозвон
625673,4784167,3339623,49607,2020-03-27 12:29:12,Оформление,Узнать результаты приема,Нет обратной связи от руководителя
625674,4784167,3339623,49607,2020-03-30 10:05:07,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625675,4784167,3339623,49607,2020-03-31 08:02:32,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625676,4784167,3339623,49607,2020-03-31 16:01:37,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625679,4784167,3339623,49607,2020-04-01 14:03:02,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625678,4784167,3339623,49607,2020-04-02 12:03:30,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625677,4784167,3339623,49607,2020-04-02 16:04:24,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
625662,4784167,3339623,49607,2020-04-02 16:04:53,Смена вакансии,NaN,NaN
625661,4784167,3339623,49607,2020-04-02 16:05:25,Смена вакансии,NaN,ОС не предоставлена руководителем
625660,4784167,3339623,49607,2020-04-03 14:05:14,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625659,4784167,3339623,49607,2020-04-06 12:05:45,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625658,4784167,3339623,49607,2020-04-07 07:02:05,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625657,4784167,3339623,49607,2020-04-07 13:03:12,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625656,4784167,3339623,49607,2020-04-08 08:02:09,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625655,4784167,3339623,49607,2020-04-08 13:06:14,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625654,4784167,3339623,49607,2020-04-09 08:05:59,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625653,4784167,3339623,49607,2020-04-09 13:07:51,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625652,4784167,3339623,49607,2020-04-10 08:04:03,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625651,4784167,3339623,49607,2020-04-10 13:04:36,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625650,4784167,3339623,49607,2020-04-13 08:05:46,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625648,4784167,3339623,49607,2020-04-13 16:15:21,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
625649,4784167,3339623,49607,2020-04-13 16:15:22,Оформление,Предоставить обратную связь по кандидату,Отказ руководителя

In [4]:
df[df['id_applicant'] == 4700471].drop(['id_log', 'is_open_action', 'position_name'], axis=1).sort_values('action_date')

,id_applicant,id_partner,department_id,action_date,stage_name,activity_name,result_name
128776,4700471,3797151,30806,2020-02-28 09:26:22,Создание кандидата,NaN,NaN
397218,4700471,3797151,30806,2020-02-28 09:26:31,Обработка,Провести первичную обработку,Подходит
397243,4700471,3797151,30806,2020-02-28 09:26:33,Обработка,Проверка формы обращения,Не резерв
397219,4700471,3797151,30806,2020-02-28 09:26:34,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
397220,4700471,3797151,30806,2020-02-28 09:26:36,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
397221,4700471,3797151,30806,2020-02-28 09:26:37,СБ,Узнать результаты СБ,Подготовлена
397222,4700471,3797151,30806,2020-02-28 10:55:17,СБ,Узнать результаты СБ,Подходит
397240,4700471,3797151,30806,2020-02-28 10:55:18,СБ,Проверка формы обращения,Не резерв
397223,4700471,3797151,30806,2020-02-28 15:47:48,Оформление,Назначить время на оформление,Недозвон
397224,4700471,3797151,30806,2020-02-28 17:35:11,Оформление,Назначить время на оформление,Недозвон
397225,4700471,3797151,30806,2020-02-29 12:46:38,Оформление,Назначить время на оформление,Время назначено
397226,4700471,3797151,30806,2020-03-03 12:00:01,Оформление,Узнать результаты приема,Недозвон
397227,4700471,3797151,30806,2020-03-03 12:14:28,Оформление,Узнать результаты приема,Перенос звонка
397228,4700471,3797151,30806,2020-03-10 09:44:25,Оформление,Узнать результаты приема,Недозвон
397229,4700471,3797151,30806,2020-03-10 10:43:04,Оформление,Узнать результаты приема,Нет обратной связи от руководителя
397230,4700471,3797151,30806,2020-03-11 09:03:12,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397231,4700471,3797151,30806,2020-03-11 17:01:54,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397232,4700471,3797151,30806,2020-03-12 15:01:42,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397233,4700471,3797151,30806,2020-03-13 14:02:09,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397234,4700471,3797151,30806,2020-03-16 12:02:33,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397235,4700471,3797151,30806,2020-03-17 10:03:05,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397236,4700471,3797151,30806,2020-03-18 08:01:21,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397237,4700471,3797151,30806,2020-03-18 16:03:21,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397238,4700471,3797151,30806,2020-03-19 14:04:08,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397239,4700471,3797151,30806,2020-03-20 12:02:41,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397241,4700471,3797151,30806,2020-03-23 10:04:03,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397242,4700471,3797151,30806,2020-03-24 08:02:37,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397244,4700471,3797151,30806,2020-03-24 16:02:47,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397245,4700471,3797151,30806,2020-03-25 14:02:46,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
397248,4700471,3797151,30806,2020-04-01 16:33:04,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
397249,4700471,3797151,30806,2020-04-01 16:33:21,Смена вакансии,NaN,NaN

In [112]:
# df[(df['activity_name'] == 'Узнать результаты СБ') & (df['result_name'] == 'Подготовлена')]

In [5]:
df[df['id_applicant'] == 4814936].drop(['id_log','is_open_action', 'position_name'], axis=1).sort_values('action_date')

,id_applicant,id_partner,department_id,action_date,stage_name,activity_name,result_name
181887,4814936,3856819,12114,2020-03-27 09:21:02,Создание кандидата,NaN,NaN
673967,4814936,3856819,12114,2020-03-27 09:21:22,Обработка,Провести первичную обработку,Подходит
673966,4814936,3856819,12114,2020-03-27 09:21:23,Обработка,Проверка формы обращения,Не резерв
673965,4814936,3856819,12114,2020-03-27 09:21:34,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
673964,4814936,3856819,12114,2020-03-27 14:30:20,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос кандидата
673963,4814936,3856819,12114,2020-03-27 14:30:40,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
673962,4814936,3856819,12114,2020-03-29 12:42:38,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос кандидата
673961,4814936,3856819,12114,2020-03-29 12:42:51,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
673960,4814936,3856819,12114,2020-03-31 16:12:17,Интервью с руководителем,Узнать результаты интервью с руководителем,Нет обратной связи от руководителя
673959,4814936,3856819,12114,2020-04-01 14:01:52,Интервью с руководителем,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673958,4814936,3856819,12114,2020-04-01 15:32:06,Интервью с руководителем,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
673957,4814936,3856819,12114,2020-04-01 15:32:12,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
673956,4814936,3856819,12114,2020-04-01 15:32:15,СБ,Подготовить анкету кандидата,Подготовлена
673954,4814936,3856819,12114,2020-04-02 08:25:42,СБ,Узнать результаты СБ,Подходит
673955,4814936,3856819,12114,2020-04-02 08:25:43,СБ,Проверка формы обращения,Не резерв
673953,4814936,3856819,12114,2020-04-02 14:28:25,Оформление,Назначить время на оформление,Время назначено
673952,4814936,3856819,12114,2020-04-02 14:28:29,Оформление,Узнать результаты приема,Нет обратной связи от руководителя
673951,4814936,3856819,12114,2020-04-03 12:04:45,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673950,4814936,3856819,12114,2020-04-06 10:28:28,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673949,4814936,3856819,12114,2020-04-07 05:01:26,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673948,4814936,3856819,12114,2020-04-07 13:01:45,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673947,4814936,3856819,12114,2020-04-08 08:01:05,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673946,4814936,3856819,12114,2020-04-08 13:05:04,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673945,4814936,3856819,12114,2020-04-09 08:02:50,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673944,4814936,3856819,12114,2020-04-09 13:04:14,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673943,4814936,3856819,12114,2020-04-10 08:02:27,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673942,4814936,3856819,12114,2020-04-10 13:03:15,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673941,4814936,3856819,12114,2020-04-13 08:03:59,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
673940,4814936,3856819,12114,2020-04-13 16:14:06,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
732463,4814936,3856819,12114,2020-04-23 16:26:11,Оформление,Предоставить обратную связь по кандидату,NaN

In [25]:
# df[(df['activity_name'] == 'Предоставить обратную связь по кандидату') & (df['result_name'].isnull())]

In [19]:
df[df['id_applicant'] == 4845963].drop(['id_log', 'is_open_action', 'position_name'], axis=1).sort_values(['action_date', 'activity_name'])

,id_applicant,id_partner,department_id,action_date,stage_name,activity_name,result_name
189055,4845963,3871526,43717,2020-04-05 12:23:44,Создание кандидата,NaN,NaN
236528,4845963,3871526,43717,2020-04-05 12:23:52,Обработка,Проверка формы обращения,Не резерв
236527,4845963,3871526,43717,2020-04-05 12:23:52,Обработка,Провести первичную обработку,Подходит
236526,4845963,3871526,43717,2020-04-05 12:24:02,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
236525,4845963,3871526,43717,2020-04-12 13:58:59,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон
236524,4845963,3871526,43717,2020-04-13 19:31:52,Интервью с руководителем,Узнать результаты интервью с руководителем,Нет обратной связи от руководителя
736413,4845963,3871526,43717,2020-04-23 16:26:11,Интервью с руководителем,Предоставить обратную связь по кандидату,NaN

In [8]:
# df[df['id_applicant'] == 4811435].drop(['id_log', 'is_active_action', 'is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [74]:
df_new = df[['stage_name','activity_name','result_name']]
df_new = df_new.drop_duplicates().sort_values('stage_name')
df_new = df_new.reset_index(drop=True)
df_new

,stage_name,activity_name,result_name
0,Выход на работу,NaN,Недозвон
1,Выход на работу,NaN,Отказ кандидата
2,Выход на работу,NaN,ОС не предоставлена руководителем
3,Интервью с руководителем,Предоставить обратную связь по кандидату,Встреча назначена
4,Интервью с руководителем,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
...,...,...,...
99,Смена вакансии,NaN,ОС не предоставлена руководителем
100,Смена вакансии,NaN,Недозвон
101,Смена вакансии,NaN,NaN
102,Создание кандидата,NaN,NaN
103,Черный список,Вывести из черного списка,NaN

In [75]:
df_new = df[['stage_name','activity_name','result_name']]
df_new = df_new.drop_duplicates().sort_values('stage_name')
df_new = df_new.reset_index(drop=True)
df_new
df_copy = df.copy()
df_copy[['stage_name', 'activity_name', 'result_name']] = df_copy[['stage_name', 'activity_name', 'result_name']].fillna('')
df_new[['stage_name', 'activity_name', 'result_name']] = df_new[['stage_name', 'activity_name', 'result_name']].fillna('')
df_new['count'] = 0
# df[df['stage_name'] == "Выход на работу"].shape[0]
for index, row in df_new.iterrows():
    val = df_copy[(df_copy['stage_name'] == row['stage_name']) & (df_copy['activity_name'] == row['activity_name']) & (df_copy['result_name'] == row['result_name'])].shape[0]
    df_new.at[index, 'count'] = val
df_new

,stage_name,activity_name,result_name,count
0,Выход на работу,,Недозвон,1
1,Выход на работу,,Отказ кандидата,2
2,Выход на работу,,ОС не предоставлена руководителем,16
3,Интервью с руководителем,Предоставить обратную связь по кандидату,Встреча назначена,52
4,Интервью с руководителем,Предоставить обратную связь по кандидату,ОС предоставлена руководителем,1099
...,...,...,...,...
99,Смена вакансии,,ОС не предоставлена руководителем,4
100,Смена вакансии,,Недозвон,1
101,Смена вакансии,,,9731
102,Создание кандидата,,,149735
103,Черный список,Вывести из черного списка,,54

In [77]:
df_new.sort_values('count').to_csv('unique_count.csv')

In [78]:
df_new.sort_values('stage_name').to_csv('unique_count2.csv')

In [164]:
# df[df['stage_name'] == 'Выход на работу']

In [9]:
df[df['id_applicant'] == 4824789].drop(['id_log','is_open_action', 'position_name'], axis=1).sort_values('action_date')

,id_applicant,id_partner,department_id,action_date,stage_name,activity_name,result_name
182053,4824789,3861710,30408,2020-03-31 08:00:21,Создание кандидата,NaN,NaN
261153,4824789,3861710,30408,2020-03-31 08:00:30,Обработка,Проверка формы обращения,Не резерв
261154,4824789,3861710,30408,2020-03-31 08:00:30,Обработка,Провести первичную обработку,Подходит
261152,4824789,3861710,30408,2020-03-31 08:00:31,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
261151,4824789,3861710,30408,2020-03-31 08:00:32,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
261150,4824789,3861710,30408,2020-03-31 08:00:32,СБ,Подготовить анкету кандидата,Подготовлена
261148,4824789,3861710,30408,2020-03-31 10:02:27,СБ,Узнать результаты СБ,Подходит
261149,4824789,3861710,30408,2020-03-31 10:02:28,СБ,Проверка формы обращения,Не резерв
261147,4824789,3861710,30408,2020-04-01 09:19:48,Оформление,Назначить время на оформление,Время назначено
261146,4824789,3861710,30408,2020-04-01 09:19:51,Оформление,Узнать результаты приема,Нет обратной связи от руководителя
261145,4824789,3861710,30408,2020-04-01 16:04:32,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261144,4824789,3861710,30408,2020-04-02 14:06:37,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261143,4824789,3861710,30408,2020-04-03 12:04:29,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261142,4824789,3861710,30408,2020-04-03 16:04:25,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
261141,4824789,3861710,30408,2020-04-03 16:04:29,Оформление,Узнать результаты приема,Принят
261140,4824789,3861710,30408,2020-04-03 16:04:59,Выход на работу,NaN,ОС не предоставлена руководителем
261139,4824789,3861710,30408,2020-04-06 14:04:49,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261138,4824789,3861710,30408,2020-04-07 09:01:38,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261137,4824789,3861710,30408,2020-04-07 13:06:35,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261136,4824789,3861710,30408,2020-04-08 08:04:21,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261135,4824789,3861710,30408,2020-04-08 13:07:53,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261134,4824789,3861710,30408,2020-04-09 08:03:50,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261133,4824789,3861710,30408,2020-04-09 13:05:33,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261132,4824789,3861710,30408,2020-04-10 08:03:18,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261131,4824789,3861710,30408,2020-04-10 13:04:08,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261130,4824789,3861710,30408,2020-04-13 08:05:06,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
261129,4824789,3861710,30408,2020-04-13 16:15:00,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
732546,4824789,3861710,30408,2020-04-23 16:26:11,Оформление,Предоставить обратную связь по кандидату,NaN

In [11]:
# df[df['id_applicant'] == 4782054].drop(['id_log','is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [13]:
# df[df['id_applicant'] == 4796626].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [15]:
# df[df['id_applicant'] == 4796626].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [105]:
# df[df['id_applicant'] == 4818196].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [165]:
# df[df['stage_name'] == 'Мы отказали']

In [166]:
# df[df['id_applicant'] == 4803377].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [167]:
# df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Предоставить обратную связь по кандидату')]

In [168]:
# df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Узнать результаты интервью с руководителем')]

In [169]:
# df[df['id_applicant'] == 4848496].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [4]:
df.loc[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Предоставить обратную связь по кандидату'), 'activity_name'] = 'Узнать результаты интервью с руководителем'

In [4]:
def generate_unique_csv():
    df_new = df[['stage_name','activity_name','result_name']]
    df_new = df_new.drop_duplicates().sort_values('stage_name')
    df_new = df_new.reset_index(drop=True)
    df_new
    df_copy = df.copy()
    df_copy[['stage_name', 'activity_name', 'result_name']] = df_copy[['stage_name', 'activity_name', 'result_name']].fillna('')
    df_new[['stage_name', 'activity_name', 'result_name']] = df_new[['stage_name', 'activity_name', 'result_name']].fillna('')
    df_new['count'] = 0
    for index, row in df_new.iterrows():
        val = df_copy[(df_copy['stage_name'] == row['stage_name']) & (df_copy['activity_name'] == row['activity_name']) & (df_copy['result_name'] == row['result_name'])].shape[0]
        df_new.at[index, 'count'] = val
    df_new.sort_values('stage_name').to_csv('unique_count2.csv')
    return df_new

def clientInfo(df, id):
    return df[df['id_applicant'] == id].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [6]:
df.loc[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Узнать результаты интервью с руководителем') & (df['result_name'] == 'Нет обратной связи от руководителя'), 'result_name'] = 'ОС не предоставлена руководителем'

In [8]:
df_new = generate_unique_csv()

In [7]:
df_new[(df_new['stage_name'] == 'Интервью с руководителем') & (df_new['activity_name'] == 'Узнать результаты интервью с руководителем')]

NameError: name 'df_new' is not defined

In [7]:
df.loc[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Узнать результаты интервью с руководителем') & (df['result_name'] == 'Перенос руководителя'), 'result_name'] = 'Перенос звонка'

In [16]:
df_new = generate_unique_csv()
df_new[(df_new['stage_name'] == 'Интервью с руководителем') & (df_new['activity_name'] == 'Узнать результаты интервью с руководителем')]

,stage_name,activity_name,result_name,count
5,Интервью с руководителем,Узнать результаты интервью с руководителем,Не подходит,1374
7,Интервью с руководителем,Узнать результаты интервью с руководителем,Резерв,992
9,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,17789
10,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос кандидата,2794
13,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос звонка,6592
14,Интервью с руководителем,Узнать результаты интервью с руководителем,,10909
15,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон,16979
16,Интервью с руководителем,Узнать результаты интервью с руководителем,Отказ руководителя,1590
17,Интервью с руководителем,Узнать результаты интервью с руководителем,ОС не предоставлена руководителем,6522
19,Интервью с руководителем,Узнать результаты интервью с руководителем,Черный список,4
21,Интервью с руководителем,Узнать результаты интервью с руководителем,Отказ кандидата,5825
22,Интервью с руководителем,Узнать результаты интервью с руководителем,Встреча назначена,58

In [8]:
df.loc[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Назначить интервью с руководителем') & (df['result_name'] == 'Перенос кандидата'), 'result_name'] = 'Перенос звонка'

In [178]:
df_new = generate_unique_csv()

In [179]:
# df[(df['stage_name'] == 'Интервью с руководителем') & (df['result_name'] == 'ОС предоставлена руководителем')]

In [180]:
# df[df['id_applicant'] == 4799489].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [9]:
df = df.drop(df[(df['stage_name'] == 'Интервью с руководителем') & (df['result_name'] == 'ОС предоставлена руководителем')].index)

In [12]:
df_new = generate_unique_csv()

In [183]:
df

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
0,4797513,3847682,-1,7335,2020-03-23 19:57:25,Создание кандидата,NaN,NaN,Продавец-кассир,False
3,4788965,3843286,-1,10613,2020-03-20 16:09:34,Создание кандидата,NaN,NaN,Продавец-кассир,False
4,4777310,2372866,-1,45445,2020-03-18 13:53:36,Создание кандидата,NaN,NaN,Продавец-кассир,False
11,4798971,1253935,-1,9851,2020-03-24 10:39:28,Создание кандидата,NaN,NaN,Продавец-кассир,False
13,4637426,3352131,-1,7640,2020-02-13 12:44:35,Создание кандидата,NaN,NaN,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
739675,4825142,2952699,-1,32061,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739676,4736341,936507,-1,32061,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739679,4769924,3823657,-1,32110,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739680,4683816,862865,-1,32093,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True

In [191]:
# df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Узнать результаты интервью с руководителем') & (df['result_name'] == 'Встреча назначена')]

In [17]:
# df[df['id_applicant'] == 4837354].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [ ]:
# Можно дропнуть встреча назначена при узнавании результатов

In [38]:
# df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Узнать результаты интервью с руководителем') & (df['result_name'].isnull())]

In [37]:
# df[df['id_applicant'] == 4869996].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')
# Если в каком-то действии в конце Nan, то это дроп чувака

In [40]:
df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Назначить интервью с руководителем') & (df['result_name'] == 'Подходит')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
218741,4811950,3695890,26657761,25427,2020-03-26 12:04:50,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
220799,4849738,3877121,26890280,49708,2020-04-06 13:31:42,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
221034,4835052,3867697,26811681,23921,2020-04-02 13:18:21,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
222676,4873437,3890759,27027004,7979,2020-04-10 14:51:48,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
222701,4846359,3874900,26874907,12459,2020-04-05 15:56:32,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
686066,4883300,3895331,27087805,25209,2020-04-13 15:32:50,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
687226,4862908,3884746,26963845,49767,2020-04-08 15:22:31,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
692365,4886031,3896869,27103320,9332,2020-04-14 10:13:00,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
694445,4842757,2846900,26849202,35130,2020-04-03 18:02:24,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False
694773,4885247,1956260,27099515,12871,2020-04-14 08:19:25,Интервью с руководителем,Назначить интервью с руководителем,Подходит,Продавец-кассир,False

In [51]:
# df[df['id_applicant'] == 4873437].drop(['is_open_action', 'position_name'], axis=1).sort_values('action_date')

In [10]:
df = df.drop(df[(df['stage_name'] == 'Интервью с руководителем') & (df['activity_name'] == 'Назначить интервью с руководителем') & (df['result_name'] == 'Подходит')].index)

In [14]:
df_new = generate_unique_csv()

In [15]:
df[df['stage_name'] == 'Мы отказали']
# В основном это лишний мусор, но решил пока оставить. Это состояние, куда переводят после интервью или СБ

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
221885,4803377,3850828,26680522,24908,2020-03-27 09:21:14,Мы отказали,NaN,Нет обратной связи от руководителя,Продавец-кассир,False
287899,4807811,948072,26729448,32643,2020-03-30 12:32:10,Мы отказали,NaN,В белый список,Продавец-кассир,False
333046,4813971,2975040,26697563,12973,2020-03-27 14:35:50,Мы отказали,NaN,Нет обратной связи от руководителя,Продавец-кассир,False
464338,4760133,3605084,26672709,25514,2020-03-26 16:40:37,Мы отказали,NaN,Черный список,Продавец-кассир,False
618748,4825168,3585894,26799123,46421,2020-04-02 07:58:58,Мы отказали,NaN,Не подходит,Продавец-кассир,False
664795,4812845,3855833,26731791,9757,2020-03-30 13:26:03,Мы отказали,NaN,В белый список,Продавец-кассир,False
694423,4822095,2515323,26940860,28541,2020-04-08 06:31:48,Мы отказали,NaN,В белый список,Продавец-кассир,False

In [22]:
clientInfo(df, 4803377)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
183378,4803377,3850828,-1,24908,2020-03-24 19:07:07,Создание кандидата,NaN,NaN
221887,4803377,3850828,26669376,24908,2020-03-26 15:53:51,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон
221886,4803377,3850828,26680483,24908,2020-03-27 09:20:12,Интервью с руководителем,Узнать результаты интервью с руководителем,Не подходит
221885,4803377,3850828,26680522,24908,2020-03-27 09:21:14,Мы отказали,NaN,Нет обратной связи от руководителя
221883,4803377,3850828,26694305,24908,2020-03-27 13:39:26,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
221882,4803377,3850828,26694314,24908,2020-03-27 13:39:33,СБ,Подготовить анкету кандидата,Подготовлена
221881,4803377,3850828,26694323,24908,2020-03-27 13:39:46,СБ,Узнать результаты СБ,Подходит
221880,4803377,3850828,26694324,24908,2020-03-27 13:39:47,СБ,Проверка формы обращения,Не резерв
221879,4803377,3850828,26705446,24908,2020-03-27 17:37:52,Оформление,Назначить время на оформление,Время назначено
221878,4803377,3850828,26780326,24908,2020-04-01 09:10:51,Оформление,Узнать результаты приема,Недозвон
221877,4803377,3850828,27064732,24908,2020-04-12 15:12:29,Оформление,Узнать результаты приема,Недозвон
733470,4803377,3850828,-1,24908,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN

In [34]:
df[(df['stage_name'] == 'Обработка') & (df['activity_name'] == 'Проверка формы обращения') & (df['result_name'] == 'Подходит')]

Empty DataFrame
Columns: [id_applicant, id_partner, id_log, department_id, action_date, stage_name, activity_name, result_name, position_name, is_open_action]
Index: []

In [35]:
# clientInfo(df, 4855286)

In [11]:
df = df.drop(df[(df['stage_name'] == 'Обработка') & (df['activity_name'] == 'Проверка формы обращения') & (df['result_name'] == 'Подходит')].index)

In [32]:
df_new = generate_unique_csv()

In [13]:
df[(df['stage_name'] == 'Оформление') & (df['activity_name'] == 'Узнать результаты приема')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
214909,4784277,3840984,26664817,5960,2020-03-26 14:13:07,Оформление,Узнать результаты приема,Отказ кандидата,Продавец-кассир,False
214910,4784277,3840984,26639308,5960,2020-03-25 17:35:49,Оформление,Узнать результаты приема,Недозвон,Продавец-кассир,False
214958,4774172,3835783,26666690,31992,2020-03-26 14:48:20,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
214962,4813502,3821610,26668701,18141,2020-03-26 15:39:35,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
214980,4813678,2057903,26669783,31462,2020-03-26 16:01:07,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
739646,4859722,3757095,-1,32011,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN,Продавец-кассир,True
739647,4846458,3831915,-1,32011,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN,Продавец-кассир,True
739660,4862004,3884234,-1,31960,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN,Продавец-кассир,True
739661,4847420,3792798,-1,31960,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN,Продавец-кассир,True
739674,4858661,3882286,-1,32061,2020-04-23 16:26:11,Оформление,Узнать результаты приема,NaN,Продавец-кассир,True

In [21]:
# clientInfo(df, 4859722)

In [ ]:
df.loc[(df['stage_name'] == 'Оформление') & (df['activity_name'] == 'Узнать результаты приема'), 'activity_name'] = 'Узнать результаты интервью с руководителем'

In [24]:
df[(df['stage_name'] == 'Смена вакансии')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
214838,4799096,3388458,26642796,30059,2020-03-26 08:05:14,Смена вакансии,NaN,NaN,Продавец-кассир,False
214898,4795061,3742188,26650264,11473,2020-03-26 10:18:28,Смена вакансии,NaN,NaN,Продавец-кассир,False
214902,4812039,2058461,26689072,34670,2020-03-27 12:00:30,Смена вакансии,NaN,NaN,Продавец-кассир,False
214928,4805065,3851754,26687231,31603,2020-03-27 11:28:02,Смена вакансии,NaN,NaN,Продавец-кассир,False
214934,4810900,3854856,26689533,24877,2020-03-27 12:03:08,Смена вакансии,NaN,NaN,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
704549,4826495,3848893,26823299,9400,2020-04-02 18:14:28,Смена вакансии,NaN,NaN,Продавец-кассир,False
704595,4797098,3847494,26684028,11389,2020-03-27 10:29:21,Смена вакансии,NaN,NaN,Продавец-кассир,False
704608,4799489,3803952,26732475,19050,2020-03-30 13:39:29,Смена вакансии,NaN,NaN,Продавец-кассир,False
704617,4829912,3864508,26802382,10685,2020-04-02 09:47:46,Смена вакансии,NaN,NaN,Продавец-кассир,False
704646,4828062,2923389,26772773,25608,2020-03-31 16:15:31,Смена вакансии,NaN,NaN,Продавец-кассир,False

In [30]:
clientInfo(df, 4799096)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
1808,4799096,3388458,-1,30059,2020-03-24 10:52:47,Создание кандидата,NaN,NaN
214837,4799096,3388458,26578035,30059,2020-03-24 10:53:03,Обработка,Провести первичную обработку,Подходит
214834,4799096,3388458,26578038,30059,2020-03-24 10:53:04,Обработка,Проверка формы обращения,Не резерв
214839,4799096,3388458,26578040,30059,2020-03-24 10:53:06,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
214835,4799096,3388458,26578046,30059,2020-03-24 10:53:16,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос звонка
214836,4799096,3388458,26623129,30059,2020-03-25 13:15:22,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон
214838,4799096,3388458,26642796,30059,2020-03-26 08:05:14,Смена вакансии,NaN,NaN

In [35]:
df[(df['stage_name'] == 'Не прошел СБ')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
215323,4509821,3694092,26973768,6552,2020-04-09 06:59:29,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
215376,4484438,3679681,26907121,20375,2020-04-07 06:59:25,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
215456,4490980,3597781,26876696,30511,2020-04-06 08:00:36,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
215457,4485973,3487032,26876692,10795,2020-04-06 08:00:31,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
215475,4496296,3655253,26974574,12807,2020-04-09 07:59:13,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
739675,4825142,2952699,-1,32061,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739676,4736341,936507,-1,32061,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739679,4769924,3823657,-1,32110,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
739680,4683816,862865,-1,32093,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True

In [45]:
clientInfo(df, 4782853)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
214300,4782853,2753502,-1,32110,2020-03-19 13:41:49,Создание кандидата,NaN,NaN
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN

In [46]:
df[(df['stage_name'] == 'Черный список')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
704772,4538990,3002793,-1,42954,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
704907,4539272,2098346,-1,42954,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
704922,4758392,3197557,-1,10708,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
705423,4542608,3622649,-1,30991,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
705424,4541709,2474617,-1,30991,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
705425,4541218,2750312,-1,30991,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
706616,4829525,3864281,-1,11890,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
706814,4814273,3516801,-1,36545,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
707163,4822333,3824380,-1,7947,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
707334,4832169,3290102,-1,11755,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
709552,4847557,3873113,-1,11448,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
709594,4838320,3869749,-1,49734,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
711644,4838801,3870090,-1,8007,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
712044,4705147,2820941,-1,6285,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
712469,4646885,3300338,-1,10450,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
713004,4541425,2468306,-1,24133,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
713005,4541046,3276046,-1,24133,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
713006,4538390,2551249,-1,24133,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714789,4527470,3619546,-1,11303,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714888,4541623,2618832,-1,8156,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714889,4541610,3134725,-1,8156,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714890,4538726,2400952,-1,8156,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714891,4538656,1896327,-1,8156,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714892,4538598,2576413,-1,8156,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
714951,4833808,3759937,-1,32606,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715245,4684198,2809964,-1,35465,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715263,4538673,2979225,-1,8177,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715443,4572333,2097646,-1,36776,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715554,4760133,3605084,-1,25514,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715631,4541939,2902595,-1,25514,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715632,4541149,2736750,-1,25514,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715633,4538635,1539177,-1,25514,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715928,4539090,2096091,-1,30011,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
715929,4538296,2307716,-1,30011,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
716294,4539151,1040837,-1,34061,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
716295,4538676,1959648,-1,34061,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
716339,4538765,2933853,-1,35895,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
716340,4538610,2532013,-1,35895,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
716383,4541953,2154777,-1,35991,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
718219,4821320,3856217,-1,33730,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
718885,4541982,637131,-1,45858,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
718886,4541833,2732093,-1,45858,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
719090,4801774,783604,-1,7692,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
719767,4633383,3586575,-1,6230,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
719780,4676087,3774841,-1,10791,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
720838,4683491,3641573,-1,49427,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
722449,4521815,2596099,-1,11377,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
722568,4579388,3652507,-1,48245,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
723461,4724974,3597619,-1,26888,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
726136,4790505,3844094,-1,47391,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
726959,4748959,2638586,-1,49574,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
738049,4696983,3789095,-1,12398,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
738298,4538891,2392786,-1,8133,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True
739092,4700505,3797137,-1,24853,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN,Продавец-кассир,True

In [51]:
clientInfo(df, 4579388)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
130893,4579388,3652507,-1,48245,2020-01-31 17:23:54,Создание кандидата,NaN,NaN
722568,4579388,3652507,-1,48245,2020-04-23 16:26:11,Черный список,Вывести из черного списка,NaN

In [7]:
df[(df['stage_name'] == 'Оформление') & (df['result_name'] == 'Принят')]

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
214958,4774172,3835783,26666690,31992,2020-03-26 14:48:20,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
214962,4813502,3821610,26668701,18141,2020-03-26 15:39:35,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
214980,4813678,2057903,26669783,31462,2020-03-26 16:01:07,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
215047,4813843,3822462,26671477,30354,2020-03-26 16:21:38,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
215065,4766031,3831548,26674667,31760,2020-03-26 17:16:26,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
...,...,...,...,...,...,...,...,...,...,...
704170,4854560,3855417,26915732,49671,2020-04-07 11:05:40,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
704241,4883157,3860226,27087224,10660,2020-04-13 15:18:28,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
704254,4846293,3856487,27087777,7649,2020-04-13 15:32:12,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
704464,4864742,1593647,27105932,23665,2020-04-14 11:07:42,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
704686,4786759,3842225,26635619,6260,2020-03-25 16:28:25,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False

In [9]:
clientInfo(df, 4766031)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
6735,4766031,3831548,-1,31760,2020-03-16 13:23:00,Создание кандидата,NaN,NaN
215067,4766031,3831548,26657648,31760,2020-03-26 12:04:07,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем
215066,4766031,3831548,26674666,31760,2020-03-26 17:16:21,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем
215065,4766031,3831548,26674667,31760,2020-03-26 17:16:26,Оформление,Узнать результаты приема,Принят

In [12]:
df[(df['department_id'] == 31760)].sort_values('')

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
6735,4766031,3831548,-1,31760,2020-03-16 13:23:00,Создание кандидата,NaN,NaN,Продавец-кассир,False
1083,4793468,3768121,-1,31760,2020-03-23 11:43:44,Создание кандидата,NaN,NaN,Продавец-кассир,False
20787,4811430,2345146,-1,31760,2020-03-26 11:16:01,Создание кандидата,NaN,NaN,Продавец-кассир,False
574651,4811430,2345146,26654161,31760,2020-03-26 11:16:16,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
574650,4811430,2345146,26654162,31760,2020-03-26 11:16:18,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
574649,4811430,2345146,26654185,31760,2020-03-26 11:16:35,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
215067,4766031,3831548,26657648,31760,2020-03-26 12:04:07,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
293788,4793468,3768121,26674256,31760,2020-03-26 17:08:17,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон,Продавец-кассир,False
215066,4766031,3831548,26674666,31760,2020-03-26 17:16:21,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем,Продавец-кассир,False
215065,4766031,3831548,26674667,31760,2020-03-26 17:16:26,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
574648,4811430,2345146,26675787,31760,2020-03-26 17:38:54,Интервью с руководителем,Узнать результаты интервью с руководителем,Нет обратной связи от руководителя,Продавец-кассир,False
293787,4793468,3768121,26680004,31760,2020-03-27 09:10:18,Интервью с руководителем,Узнать результаты интервью с руководителем,Отказ кандидата,Продавец-кассир,False
574647,4811430,2345146,26684820,31760,2020-03-27 10:45:31,Интервью с руководителем,Предоставить обратную связь по кандидату,ОС предоставлена руководителем,Продавец-кассир,False
574646,4811430,2345146,26684833,31760,2020-03-27 10:45:51,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос звонка,Продавец-кассир,False
574645,4811430,2345146,26713045,31760,2020-03-29 11:38:45,Интервью с руководителем,Узнать результаты интервью с руководителем,Резерв,Продавец-кассир,False
112962,4820957,3822716,-1,31760,2020-03-30 10:23:29,Создание кандидата,NaN,NaN,Продавец-кассир,False
372072,4820957,3822716,26723913,31760,2020-03-30 10:23:47,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
372071,4820957,3822716,26723915,31760,2020-03-30 10:23:48,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
372070,4820957,3822716,26723944,31760,2020-03-30 10:24:47,Интервью с руководителем,Назначить интервью с руководителем,Перенос звонка,Продавец-кассир,False
372069,4820957,3822716,26788768,31760,2020-04-01 12:50:01,Интервью с руководителем,Назначить интервью с руководителем,Перенос звонка,Продавец-кассир,False
37686,4843419,3873203,-1,31760,2020-04-04 09:33:50,Создание кандидата,NaN,NaN,Продавец-кассир,False
414695,4843419,3873203,26853582,31760,2020-04-04 09:34:17,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
414694,4843419,3873203,26853585,31760,2020-04-04 09:34:18,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
414693,4843419,3873203,26853589,31760,2020-04-04 09:34:19,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
414692,4843419,3873203,26853594,31760,2020-04-04 09:34:19,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,False
414691,4843419,3873203,26853595,31760,2020-04-04 09:34:20,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,False
372068,4820957,3822716,26863262,31760,2020-04-04 14:52:44,Интервью с руководителем,Назначить интервью с руководителем,Недозвон,Продавец-кассир,False
414689,4843419,3873203,26865231,31760,2020-04-04 16:43:08,СБ,Узнать результаты СБ,Подходит,Продавец-кассир,False
414690,4843419,3873203,26865233,31760,2020-04-04 16:43:10,СБ,Проверка формы обращения,Не резерв,Продавец-кассир,False
372067,4820957,3822716,26866370,31760,2020-04-05 08:11:49,Интервью с руководителем,Назначить интервью с руководителем,Недозвон,Продавец-кассир,False
414688,4843419,3873203,26873534,31760,2020-04-05 14:03:45,Оформление,Назначить время на оформление,Недозвон,Продавец-кассир,False
45633,4864022,3885394,-1,31760,2020-04-08 17:26:40,Создание кандидата,NaN,NaN,Продавец-кассир,False
287228,4864022,3885394,26970122,31760,2020-04-08 17:26:57,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
287227,4864022,3885394,26970123,31760,2020-04-08 17:26:58,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
287226,4864022,3885394,26970124,31760,2020-04-08 17:26:59,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
287225,4864022,3885394,26970126,31760,2020-04-08 17:27:01,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,False
287224,4864022,3885394,26970127,31760,2020-04-08 17:27:02,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,False
287223,4864022,3885394,26980395,31760,2020-04-09 10:16:35,СБ,Узнать результаты СБ,Не подходит,Продавец-кассир,False
287222,4864022,3885394,26986594,31760,2020-04-09 12:08:14,Не прошел СБ,Вывести из черного списка,В белый список,Продавец-кассир,False
25600,4866765,3885394,-1,31760,2020-04-09 12:09:23,Создание кандидата,NaN,NaN,Продавец-кассир,False
371236,4866765,3885394,26986701,31760,2020-04-09 12:10:03,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
371235,4866765,3885394,26986703,31760,2020-04-09 12:10:05,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
371234,4866765,3885394,26986705,31760,2020-04-09 12:10:06,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
371233,4866765,3885394,26986706,31760,2020-04-09 12:10:07,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,False
371232,4866765,3885394,26986707,31760,2020-04-09 12:10:08,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,False
414687,4843419,3873203,26990306,31760,2020-04-09 13:04:26,Оформление,Назначить время на оформление,Недозвон,Продавец-кассир,False
371231,4866765,3885394,26993008,31760,2020-04-09 13:49:06,СБ,Узнать результаты СБ,Не подходит,Продавец-кассир,False
414686,4843419,3873203,27016628,31760,2020-04-10 10:59:17,Оформление,Назначить время на оформление,Отказ кандидата,Продавец-кассир,False
706442,4866765,3885394,-1,31760,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True
721189,4820957,3822716,-1,31760,2020-04-23 16:26:11,Интервью с руководителем,Назначить интервью с руководителем,NaN,Продавец-кассир,True

In [18]:
clientInfo(df, 4866765)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
25600,4866765,3885394,-1,31760,2020-04-09 12:09:23,Создание кандидата,NaN,NaN
371236,4866765,3885394,26986701,31760,2020-04-09 12:10:03,Обработка,Провести первичную обработку,Подходит
371235,4866765,3885394,26986703,31760,2020-04-09 12:10:05,Обработка,Проверка формы обращения,Не резерв
371234,4866765,3885394,26986705,31760,2020-04-09 12:10:06,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена
371233,4866765,3885394,26986706,31760,2020-04-09 12:10:07,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит
371232,4866765,3885394,26986707,31760,2020-04-09 12:10:08,СБ,Подготовить анкету кандидата,Подготовлена
371231,4866765,3885394,26993008,31760,2020-04-09 13:49:06,СБ,Узнать результаты СБ,Не подходит
706442,4866765,3885394,-1,31760,2020-04-23 16:26:11,Не прошел СБ,Вывести из черного списка,NaN

In [55]:
df[(df['stage_name'] == 'Смена вакансии') & (df['position_name'] == 'Продавец-кассир')].head(30)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
214838,4799096,3388458,26642796,30059,2020-03-26 08:05:14,Смена вакансии,NaN,NaN,Продавец-кассир,False
214898,4795061,3742188,26650264,11473,2020-03-26 10:18:28,Смена вакансии,NaN,NaN,Продавец-кассир,False
214902,4812039,2058461,26689072,34670,2020-03-27 12:00:30,Смена вакансии,NaN,NaN,Продавец-кассир,False
214928,4805065,3851754,26687231,31603,2020-03-27 11:28:02,Смена вакансии,NaN,NaN,Продавец-кассир,False
214934,4810900,3854856,26689533,24877,2020-03-27 12:03:08,Смена вакансии,NaN,NaN,Продавец-кассир,False
214977,4798209,3848067,26644999,33667,2020-03-26 09:07:52,Смена вакансии,NaN,NaN,Продавец-кассир,False
214997,4801837,3847036,26647473,12823,2020-03-26 09:44:08,Смена вакансии,NaN,NaN,Продавец-кассир,False
215017,4783145,3840392,26670796,20066,2020-03-26 16:10:23,Смена вакансии,NaN,NaN,Продавец-кассир,False
215169,4812656,3843484,26707605,31401,2020-03-28 09:19:17,Смена вакансии,NaN,NaN,Продавец-кассир,False
215183,4813645,3676612,26708369,12871,2020-03-28 11:15:21,Смена вакансии,NaN,NaN,Продавец-кассир,False
215294,4805112,3847751,26715261,9724,2020-03-29 14:32:06,Смена вакансии,NaN,NaN,Продавец-кассир,False
215300,4832906,3866340,26841022,11244,2020-04-03 14:53:24,Смена вакансии,NaN,NaN,Продавец-кассир,False
215380,4848718,3876460,26924786,9728,2020-04-07 13:30:01,Смена вакансии,NaN,NaN,Продавец-кассир,False
215520,4814690,3856700,26764875,44882,2020-03-31 13:26:57,Смена вакансии,NaN,NaN,Продавец-кассир,False
215572,4852512,3878763,26925696,7656,2020-04-07 13:48:40,Смена вакансии,NaN,NaN,Продавец-кассир,False
215714,4869912,3488704,27025008,32234,2020-04-10 13:59:59,Смена вакансии,NaN,NaN,Продавец-кассир,False
215720,4855037,3880325,26944309,10240,2020-04-08 09:09:49,Смена вакансии,NaN,NaN,Продавец-кассир,False
215767,4861426,3679248,26961660,10367,2020-04-08 14:36:39,Смена вакансии,NaN,NaN,Продавец-кассир,False
215845,4870481,3889040,27028001,7544,2020-04-10 15:18:13,Смена вакансии,NaN,NaN,Продавец-кассир,False
215853,4807241,3397948,26840389,31934,2020-04-03 14:39:40,Смена вакансии,NaN,NaN,Продавец-кассир,False
216083,4868935,3565543,27028816,12527,2020-04-10 15:38:55,Смена вакансии,NaN,NaN,Продавец-кассир,False
216135,4833043,3866160,26854079,44437,2020-04-04 09:48:34,Смена вакансии,NaN,NaN,Продавец-кассир,False
216154,4836259,3863716,26841461,30269,2020-04-03 15:01:15,Смена вакансии,NaN,NaN,Продавец-кассир,False
216167,4859959,3883099,26946717,45461,2020-04-08 10:07:00,Смена вакансии,NaN,NaN,Продавец-кассир,False
216177,4823965,3857336,26816860,45536,2020-04-02 15:10:47,Смена вакансии,NaN,NaN,Продавец-кассир,False
216241,4856906,3857630,26930994,10596,2020-04-07 15:33:59,Смена вакансии,NaN,NaN,Продавец-кассир,False
216245,4831592,3865560,26825629,9673,2020-04-03 08:41:01,Смена вакансии,NaN,NaN,Продавец-кассир,False
216320,4841202,3871782,26949097,29508,2020-04-08 10:52:23,Смена вакансии,NaN,NaN,Продавец-кассир,False
216330,4860161,3883196,26948316,9859,2020-04-08 10:36:34,Смена вакансии,NaN,NaN,Продавец-кассир,False
216341,4848223,3876123,26949287,10679,2020-04-08 10:55:43,Смена вакансии,NaN,NaN,Продавец-кассир,False

In [59]:
# clientInfo(df, 4799489)
df[df['id_applicant'] == 4831592].sort_values('action_date')

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
36831,4831592,3865560,-1,9673,2020-04-01 14:22:45,Создание кандидата,NaN,NaN,Продавец-кассир,False
216242,4831592,3865560,26791885,9673,2020-04-01 14:22:56,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
216243,4831592,3865560,26791887,9673,2020-04-01 14:22:57,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
216244,4831592,3865560,26791903,9673,2020-04-01 14:23:06,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
216245,4831592,3865560,26825629,9673,2020-04-03 08:41:01,Смена вакансии,NaN,NaN,Продавец-кассир,False

In [23]:
df[(df['department_id'] == 11473)].sort_values('action_date')

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
44660,4760317,3828579,-1,11473,2020-03-13 16:36:08,Создание кандидата,NaN,NaN,Продавец-кассир,False
2225,4795061,3742188,-1,11473,2020-03-23 14:11:19,Создание кандидата,NaN,NaN,Продавец-кассир,False
214897,4795061,3742188,26553351,11473,2020-03-23 14:11:47,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
214896,4795061,3742188,26553353,11473,2020-03-23 14:11:49,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
214895,4795061,3742188,26553355,11473,2020-03-23 14:11:50,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
214894,4795061,3742188,26553384,11473,2020-03-23 14:12:24,Интервью с руководителем,Узнать результаты интервью с руководителем,Перенос звонка,Продавец-кассир,False
214893,4795061,3742188,26597615,11473,2020-03-24 16:18:49,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон,Продавец-кассир,False
214892,4795061,3742188,26624820,11473,2020-03-25 13:46:05,Интервью с руководителем,Узнать результаты интервью с руководителем,Недозвон,Продавец-кассир,False
662761,4760317,3828579,26642637,11473,2020-03-26 08:03:10,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
214898,4795061,3742188,26650264,11473,2020-03-26 10:18:28,Смена вакансии,NaN,NaN,Продавец-кассир,False
662760,4760317,3828579,26670178,11473,2020-03-26 16:03:29,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
3960,4813711,3779938,-1,11473,2020-03-26 16:04:55,Создание кандидата,NaN,NaN,Продавец-кассир,False
382359,4813711,3779938,26670504,11473,2020-03-26 16:05:24,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,False
382352,4813711,3779938,26670507,11473,2020-03-26 16:05:25,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,False
382354,4813711,3779938,26670514,11473,2020-03-26 16:05:26,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,False
382353,4813711,3779938,26670511,11473,2020-03-26 16:05:26,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,False
382355,4813711,3779938,26670515,11473,2020-03-26 16:05:27,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,False
382356,4813711,3779938,26670516,11473,2020-03-26 16:05:28,СБ,Узнать результаты СБ,Подходит,Продавец-кассир,False
382357,4813711,3779938,26670518,11473,2020-03-26 16:05:28,СБ,Проверка формы обращения,Не резерв,Продавец-кассир,False
382358,4813711,3779938,26670519,11473,2020-03-26 16:05:29,Оформление,Назначить время на оформление,Время назначено,Продавец-кассир,False
382351,4813711,3779938,26670530,11473,2020-03-26 16:05:33,Оформление,Узнать результаты приема,Принят,Продавец-кассир,False
2387,4816290,3815453,-1,11473,2020-03-27 12:10:27,Создание кандидата,NaN,NaN,Продавец-кассир,False
314128,4816290,3815453,26690209,11473,2020-03-27 12:13:38,Смена вакансии,NaN,NaN,Продавец-кассир,False
662759,4760317,3828579,26695651,11473,2020-03-27 14:03:28,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662758,4760317,3828579,26727712,11473,2020-03-30 12:01:33,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662757,4760317,3828579,26753497,11473,2020-03-31 10:04:08,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662756,4760317,3828579,26778833,11473,2020-04-01 08:02:15,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662755,4760317,3828579,26795219,11473,2020-04-01 16:03:09,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662754,4760317,3828579,26814054,11473,2020-04-02 14:05:14,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662753,4760317,3828579,26833507,11473,2020-04-03 12:03:13,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,False
662752,4760317,3828579,26833509,11473,2020-04-03 12:03:14,Оформление,Предоставить обратную связь по кандидату,Отказ руководителя,Продавец-кассир,False

In [95]:
df[(df['result_name'] == 'Резерв') & (df['position_name'] == 'Продавец-кассир')].head(10)
# df.head()

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_open_action
935549,4116220,3475232,22363108,12469,2019-09-27 12:41:52,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935588,3968394,2969137,21326443,5955,2019-08-09 11:26:21,Интервью с руководителем,Назначить интервью с руководителем,Резерв,Продавец-кассир,False
935602,3534408,3149397,18307348,36460,2019-03-13 16:38:06,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935664,3339725,2605066,17198532,33981,2019-01-10 11:17:59,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935701,3543652,3154483,18365076,36233,2019-03-15 16:25:38,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935786,4102761,3467768,22264268,45851,2019-09-24 07:30:19,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935885,4077554,2260594,22130732,30846,2019-09-18 07:45:36,Интервью с руководителем,Узнать результаты интервью с руководителем,Резерв,Продавец-кассир,False
935971,3453472,3103908,17857501,35252,2019-02-14 15:22:10,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
935982,3438032,3041035,17770406,7813,2019-02-11 10:33:21,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False
936077,4034446,3428110,21787843,17857,2019-09-02 11:23:35,Обработка,Провести первичную обработку,Резерв,Продавец-кассир,False

In [106]:
clientInfo(df, 3968394)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name
1085,3968394,2969137,-1,5955,2019-08-09 11:25:57,Создание кандидата,NaN,NaN
935589,3968394,2969137,21326428,5955,2019-08-09 11:26:07,Обработка,Провести первичную обработку,Подходит
935590,3968394,2969137,21326429,5955,2019-08-09 11:26:08,Обработка,Проверка формы обращения,Не резерв
935588,3968394,2969137,21326443,5955,2019-08-09 11:26:21,Интервью с руководителем,Назначить интервью с руководителем,Резерв

In [88]:
generate_unique_csv()

,stage_name,activity_name,result_name,count
0,Выход на работу,,Принят,19
1,Выход на работу,,Назначить время на оформление/медосмотр,1
2,Выход на работу,,Время назначено,5
3,Выход на работу,,Отказ кандидата,1
4,Выход на работу,,Недозвон,18
...,...,...,...,...
257,Создание кандидата,,,683044
258,Черный список,Вывести из черного списка,,195
259,Черный список,Вывести из черного списка,В белый список,51
260,Черный список,Вывести из черного списка,Черный список,1
261,Черный список,Вывести из черного списка,Недозвон,1

In [93]:
df[df['position_name'] != 'Продавец-кассир'].count()

id_applicant      0
id_partner        0
id_log            0
department_id     0
action_date       0
stage_name        0
activity_name     0
result_name       0
position_name     0
is_open_action    0
dtype: int64